kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: wM_Invoke
  namespace: wM_NoAuth_Petstore
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: https://sample-api.us-east-a.apiconnect.dev.automation.ibm.com/petstore/
      verb: CUSTOM
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
