kind: DataPowerAssembly
apiVersion: api.ibm.com/v1
metadata:
  name: assembly-GlobalWeather_Soap_Api
  namespace: DPv6_Product_GlobalWeather_Soap
  version: '1.0'
  tags: []
spec:
  x-ibm-configuration:
    type: wsdl
    phase: realized
    enforced: true
    testable: true
    gateway: datapower-api-gateway
    cors:
      enabled: true
    wsdl-definition:
      wsdl: globalweather.wsdl
      service: GlobalWeather
      port: GlobalWeatherSoap
      soap-version: '1.1'
    assembly:
      execute:
        - invoke:
            title: invoke
            target-url: http://www.webservicex.com/globalweather.asmx
            version: 2.0.0
            header-control:
              type: blocklist
              values: []
            parameter-control:
              type: blocklist
              values: []
    x-ibm-apiconnect-wsdl:
      package-version: 2.0.36
      options: {}
      messages:
        info:
          - message: >-
              The wsdl 'service' has multiple 'ports'. The api is generated
              using information in the first soap 'port'.
        warning: []
        error: []
