kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: DPv6_Plan_Soap
  namespace: DPv6_Product_GlobalWeather_Soap
  version: '1.0'
  tags: []
  description: ''
spec:
  qos:
    withQuota:
      plan-limit:
        - $ref: DPv6_Product_GlobalWeather_Soap:DPv6_Quota_Soap:1.0
