kind: MockEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: new-endpoint
  namespace: new
  version: new
  tags: []
  description: ii
spec:
  paths:
    /pet:
      put:
        defaultResponse: {}
        conditionalResponse: []
      post:
        defaultResponse:
          '201':
            response:
              $ref: default:Mock-Response-y80c5v:1.0
        conditionalResponse:
          - condition: hh
            statusCode: 209
            response:
              $ref: default:Mock-Response-r6njzt:1.0
