kind: MockEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: new-endpoint
  namespace: new
  version: new
  tags: []
  description: ii
spec:
  paths:
    /pet:
      put:
        defaultResponse: {}
        conditionalResponse: []
      post:
        defaultResponse:
          '201':
            response:
              $ref: default:Mock-Response-8le17k:1.0
