kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: new郎嗀蘒鿯𠳐𫚭𫟦𬉼𠂇⽦
  namespace: proj4bsdb
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./newapi-spec.yml
  policy-sequence:
    - $ref: proj4bsdb:vignesh:1.0
