openapi: 3.0.3
info:
  title: Singapore Air Temperature API
  x-ibm-name: weatherapi21
  version: '1'
  description: >
    Real-time air-temperature readings across Singapore, provided by the
    National Environment Agency (NEA).

    Data collected from automated weather instruments at station level; updated
    every ~5 minutes. :contentReference[oaicite:3]{index=3}
servers:
  - url: /environment
    description: Base URL for NEA environment data API
paths:
  /air-temperature:
    get:
      summary: Get air temperature readings across Singapore
      description: >
        Returns the current (or recent) air temperature observations across
        multiple stations in Singapore.

        The dataset covers May 2016 to present.
        :contentReference[oaicite:4]{index=4}
      parameters:
        - name: station_id
          in: query
          description: The station identifier to filter by a specific station (optional)
          required: false
          schema:
            type: string
            example: S101
        - name: start_time
          in: query
          description: ISO-8601 timestamp to filter readings from this time (optional)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-11-11T00:00:00+08:00'
        - name: end_time
          in: query
          description: ISO-8601 timestamp to filter readings up to this time (optional)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-11-11T12:00:00+08:00'
      responses:
        '200':
          description: Successful retrieval of air-temperature readings
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of station temperature readings
                    items:
                      $ref: '#/components/schemas/StationReading'
                  api_info:
                    $ref: '#/components/schemas/ApiInfo'
        '400':
          description: Bad request e.g., invalid query parameter
        '500':
          description: Internal server error
components:
  schemas:
    StationReading:
      type: object
      properties:
        station_id:
          type: string
          description: Unique station identifier
          example: S101
        timestamp:
          type: string
          format: date-time
          description: The time of the reading
          example: '2025-11-11T12:05:00+08:00'
        temperature:
          type: number
          format: float
          description: Air temperature in degree Celsius
          example: 29.7
      required:
        - station_id
        - timestamp
        - temperature
    ApiInfo:
      type: object
      properties:
        status:
          type: string
          description: Status of the API response
          example: healthy
        version:
          type: string
          description: API version
          example: v1
      required:
        - status
        - version
  securitySchemes:
    clientID:
      name: X-IBM-Client-Id
      in: header
      description: ''
      type: apiKey
    clientSecret:
      name: X-IBM-Client-Secret
      in: header
      description: ''
      x-key-type: client_secret
      type: apiKey
security:
  - clientID: []
    clientSecret: []
